### ISSUE TITLE
Cant install/use my sql

### ISSUE THREAD

**Issue by Qwerz-code** [jeretc/cfp#1]
I followed this tutorial: https://www.cybrary.it/0p3n/mitm-hacking-wifi-pumpkin/
At the steps with my sql i cant follow any more. Tried reinstalling it several times....
ERROR: blabla...'/var/run/mysql.sock' /2 "no such file or directory")
running kali 2.0

Would appreciate help ;)

**Comment by jeretc** [comment]
You need to start mysql service. "sudo service mysql start".

**Comment by Qwerz-code** [comment]
Thank you, i will try that! 
Somewhat stupid of me that i didn't think of activating the server haha.
