### ISSUE TITLE
credentials not working

### ISSUE THREAD

**Issue by nemew** [jeretc/cfp#2]
hello, I have followed this tutorial https://www.cybrary.it/0p3n/mitm-hacking-wifi-pumpkin/ and everything works fine. 
The phishing manager + dns spoofer works on my devices. But when I login from through the fake portal wifi-pumpkin does not receive the credentials. What am I doing wrong?

**Comment by nemew** [comment]
Do you have to do something different if your system uses Mariadb as mysql?

**Comment by nemew** [comment]
The only way this is working is through wireshark. I was able to find a way to read the login info

**Comment by jeretc** [comment]
@nemew first, this method will not work on https websites. Secondly make sure you start the mysql service first to capture and save the credentials from the login portal in to mysql database. Captured credentials can also be viewed on wifi-pumpkin itself without the use of database.

_Sent from my Samsung SM-T705 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nemew** [comment]
@jeretc Thanks for the reply. The fake-portal uses http login. The mysql service is running but when i test the login it does not show on wifi-pumpkin.
My steps are (using kali as root):
-service mysql start
-mysql -u root -p
-enter password
-USE "dbname"
-open wifi-pumpkin
-start the AP with proxy and TCP proxy off
-open dns spoofer
-launch phishing manager from the dns spoofer options
-start server with ip 10.0.0.1 using the directory /var/www/html (I have the dbconnect.php edited with the login info and database name correct)
-I clear the urls in the dns spoofer and check redirect all domains
-start attack (Dnsspoof and Phishing appears as ON in dns spoofer)
- I connect using my iphone 
-Scan using dns spoofer
- go to youtube.com and gets redirected to login page on my iphone
-I login with test credentials and nothing appears anywhere in wifi-pumpkin. here is what appears in phishing manager with no errors. and the page works fine

"[Sun Jun 18 23:30:40 2017] 10.0.0.20:59600 [404]: /hotspot-detect.html - No such file or directory
[Sun Jun 18 23:31:39 2017] 10.0.0.20:59632 [200]: /
[Sun Jun 18 23:31:39 2017] 10.0.0.20:59633 [200]: /style.css
[Sun Jun 18 23:31:40 2017] 10.0.0.20:59634 [200]: /social/twitter.png
[Sun Jun 18 23:31:40 2017] 10.0.0.20:59635 [200]: /social/fb.png
[Sun Jun 18 23:31:40 2017] 10.0.0.20:59636 [200]: /social/gplus.png
[Sun Jun 18 23:31:40 2017] 10.0.0.20:59637 [200]: /social/linkedin.png
[Sun Jun 18 23:31:40 2017] 10.0.0.20:59638 [200]: /images/secure-wifi.png
[Sun Jun 18 23:31:40 2017] 10.0.0.20:59639 [200]: /images/logo.png
[Sun Jun 18 23:31:40 2017] 10.0.0.20:59640 [404]: /images/m_1rsz_halal-old-town.jpg - No such file or directory
[Sun Jun 18 23:32:26 2017] 10.0.0.20:59645 [302]: /dbconnect.php
[Sun Jun 18 23:32:26 2017] 10.0.0.20:59646 [200]: /connect.html
[Sun Jun 18 23:32:26 2017] 10.0.0.20:59647 [200]: /connect.css
[Sun Jun 18 23:32:26 2017] 10.0.0.20:59648 [200]: /images/secure-wifi.png

**Comment by jeretc** [comment]
@nemew once you login does it show you the second page and does the captured credentials stored in the database?

**Comment by nemew** [comment]
@jeretc when I log in the second page shows with no errors. But im not sure if it stores the credentials. How can I check? I checked in /var/lib/mysql/"mydatabase" it only has 3 files. db.opt, social_login.frm, social_login.ibd. Not sure if that's where it would store it

**Comment by jeretc** [comment]
@nemew if you followed the tutorial correctly than it should store the credentials in the database. In cybrary i've shown how to check the captured credentials in mysql.
